name: flat_map
version: 0.1.0
homepage: https://github.com/JosephMoniz/dart-flat-map
description: >
  A Stream transformer for performing flat mapping on async streams
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  composite_subscription: '>=0.1.0 <0.2.0'